import createTypes from 'redux-create-action-types';

export default createTypes(
  // Login
  'LOGIN_REQUEST',
  'LOGIN_SUCCESS',
  'LOGIN_ERROR',
  'LOGOUT',
  // Register
  'REGISTER_REQUEST',
  'REGISTER_SUCCESS',
  'REGISTER_ERROR',
  'REGISTER_RESET',
  // Register skeep org
  'REGISTER_SKEEP_ORG_REQUEST',
  'REGISTER_SKEEP_ORG_SUCCESS',
  'REGISTER_SKEEP_ORG_ERROR',
  'REGISTER_SKEEP_ORG_RESET',
  // Update Account
  'UPDATE_ACCOUNT_REQUEST',
  'UPDATE_ACCOUNT_SUCCESS',
  'UPDATE_ACCOUNT_ERROR',
  // reset password
  'RESET_PASSWORD_REQUEST',
  'RESET_PASSWORD_SUCCESS',
  'RESET_PASSWORD_ERROR',
  // check reset password
  'CHECK_RESET_PASSWORD_REQUEST',
  'CHECK_RESET_PASSWORD_SUCCESS',
  'CHECK_RESET_PASSWORD_ERROR',
  // User social data
  'USER_SOCIAL_REQUEST',
  'USER_SOCIAL_SUCCESS',
  'USER_SOCIAL_ERROR',
  // forget password
  'FORGET_PASSWORD_REQUEST',
  'FORGET_PASSWORD_SUCCESS',
  'FORGET_PASSWORD_ERROR',
  // check signup token
  'CHECK_SIGNUP_TOKEN_REQUEST',
  'CHECK_SIGNUP_TOKEN_SUCCESS',
  'CHECK_SIGNUP_TOKEN_ERROR',
  // check existing email
  'CHECK_EXISTING_EMAIL_REQUEST',
  'CHECK_EXISTING_EMAIL_SUCCESS',
  'CHECK_EXISTING_EMAIL_ERROR',
  // SandBox Login
  'RESET_SANDBOX_LOGIN_INFO',
  'SANDBOX_LOGIN_REQUEST',
  'SANDBOX_LOGIN_SUCCESS',
  'SANDBOX_LOGIN_FAILURE',
  // Me beta off
  'ME_BETA_OFF_REQUEST',
  'ME_BETA_OFF_SUCCESS',
  'ME_BETA_OFF_ERROR'
);
