import createTypes from 'redux-create-action-types';

export default createTypes(
  'CREATE_SUBSCRIPTION_WITH_BRAINTREE_REQUEST',
  'CREATE_SUBSCRIPTION_WITH_BRAINTREE_SUCCESS',
  'CREATE_SUBSCRIPTION_WITH_BRAINTREE_ERROR',
  'GET_PLANS',
  'GET_PLANS_SUCCESS',
  'GET_PLANS_ERROR',
  'CREATE_SUBSCRIPTION_REQUEST',
  'CREATE_SUBSCRIPTION_SUCCESS',
  'CREATE_SUBSCRIPTION_ERROR',
  'UPDATE_CREDIT_CARD_REQUEST',
  'UPDATE_CREDIT_CARD_SUCCESS',
  'UPDATE_CREDIT_CARD_ERROR',
  'CHANGE_SUBSCRIPTION_REQUEST',
  'CHANGE_SUBSCRIPTION_SUCCESS',
  'CHANGE_SUBSCRIPTION_ERROR',
  'CANCEL_SUBSCRIPTION_REQUEST',
  'CANCEL_SUBSCRIPTION_SUCCESS',
  'CANCEL_SUBSCRIPTION_ERROR',
  'SET_FIRST_PAYMENT'
);
