import createTypes from 'redux-create-action-types';

export default createTypes(
  // GET_ME_CHILD
  'GET_ME_CHILD_REQUEST',
  'GET_ME_CHILD_SUCCESS',
  'GET_ME_CHILD_ERROR',
  'ADD_ME_CHILD_DATA',

  // ADD_ME_CHILD
  'ADD_ME_CHILD_REQUEST',
  'ADD_ME_CHILD_SUCCESS',
  'ADD_ME_CHILD_ERROR',

  // GET_ME_PROGRAM
  'GET_ME_PROGRAM_REQUEST',
  'GET_ME_PROGRAM_SUCCESS',
  'GET_ME_PROGRAM_ERROR',

  // GET_ME_CHILD_DETAILS
  'GET_ME_CHILD_DETAILS_REQUEST',
  'GET_ME_CHILD_DETAILS_SUCCESS',
  'GET_ME_CHILD_DETAILS_ERROR',

  'SET_LAST_ENTRY_DATA'
);
