import createTypes from 'redux-create-action-types';

export default createTypes(
  'GET_PROGRAM_AWARDS_REQUEST',
  'GET_PROGRAM_AWARDS_SUCCESS',
  'GET_PROGRAM_AWARDS_ERROR',

  'GET_GROUP_AWARDS_REQUEST',
  'GET_GROUP_AWARDS_SUCCESS',
  'GET_GROUP_AWARDS_ERROR',

  'CREATE_AWARDS_REQUEST',
  'CREATE_AWARDS_SUCCESS',
  'CREATE_AWARDS_ERROR',
  'CREATE_AWARDS_RESET_DATA',

  'UPDATE_AWARDS_REQUEST',
  'UPDATE_AWARDS_SUCCESS',
  'UPDATE_AWARDS_ERROR',
  'UPDATE_AWARDS_RESET_DATA',

  'GET_AWARDS_PREVEW_REQUEST',
  'GET_AWARDS_PREVEW_SUCCESS',
  'GET_AWARDS_PREVEW_ERROR',

  'RESTORE_DEFAULT_AWARDS_REQUEST',
  'RESTORE_DEFAULT_AWARDS_SUCCESS',
  'RESTORE_DEFAULT_AWARDS_ERROR',
  'RESTORE_DEFAULT_AWARDS_RESET_DATA',

  'UPDATE_AVATAR_AWARDS_REQUEST',
  'UPDATE_AVATAR_AWARDS_SUCCESS',
  'UPDATE_AVATAR_AWARDS_ERROR',

  'DELETE_AVATAR_AWARDS_REQUEST',
  'DELETE_AVATAR_AWARDS_SUCCESS',
  'DELETE_AVATAR_AWARDS_ERROR',

  'GET_PROGRAM_LEADERBOARD_REQUEST',
  'GET_PROGRAM_LEADERBOARD_SUCCESS',
  'GET_PROGRAM_LEADERBOARD_ERROR',

  'GET_GROUP_LEADERBOARD_REQUEST',
  'GET_GROUP_LEADERBOARD_SUCCESS',
  'GET_GROUP_LEADERBOARD_ERROR'
);

export interface IWardsItem {
  id: number;
  user_id: number;
  name: string;
  description: string;
  goal_id: number;
  avatar?: string;
  email: string;
  is_default_avatar?: number;
}
export interface IAwardsPreviewItem {
  attributes: any;
  id: string;
  type: string;
}
