import createTypes from 'redux-create-action-types';

export default createTypes(
  'CREATE_COMBINED_GROUP_REQUEST',
  'CREATE_COMBINED_GROUP_SUCCESS',
  'CREATE_COMBINED_GROUP_ERROR',
  'CREATE_COMBINED_GROUP_RESET_DATA',

  'GET_PROGRAM_GROUPS_REQUEST',
  'GET_PROGRAM_GROUPS_SUCCESS',
  'GET_PROGRAM_GROUPS_ERROR',
  'SET_MULTIPLE_PROGRAM_GROUPS',

  'UPDATE_PROGRAM_GROUPS_REQUEST',
  'UPDATE_PROGRAM_GROUPS_SUCCESS',
  'UPDATE_PROGRAM_GROUPS_ERROR',

  'DELETE_GROUP_REQUEST',
  'DELETE_GROUP_SUCCESS',
  'DELETE_GROUP_ERROR',

  'GET_ORGANIZER_GROUPS_REQUEST',
  'GET_ORGANIZER_GROUPS_SUCCESS',
  'GET_ORGANIZER_GROUPS_ERROR',

  'ORGANIZER_SEARCH_GROUP_REQUEST',
  'ORGANIZER_SEARCH_GROUP_SUCCESS',
  'ORGANIZER_SEARCH_GROUP_ERROR',
  'ORGANIZER_SEARCH_GROUP_RESET_DATA'
);

export interface IOrganizerGroupItem {
  type: 'organizer_group';
  group_id: string | number;
  group_name: string;
}
