import createTypes from 'redux-create-action-types';

export default createTypes(
  'CREATE_PROGRAM_REQUEST',
  'CREATE_PROGRAM_SUCCESS',
  'CREATE_PROGRAM_ERROR',
  'CREATE_PROGRAM_RESET_DATA',

  'GET_PROGRAMS_REQUEST',
  'GET_PROGRAMS_SUCCESS',
  'GET_PROGRAMS_ERROR',
  'GET_PROGRAMS_RESET_DATA',

  'GET_PROGRAM_CODE_REQUEST',
  'GET_PROGRAM_CODE_SUCCESS',
  'GET_PROGRAM_CODE_ERROR',

  'SEARCH_PROGRAMS_REQUEST',
  'SEARCH_PROGRAMS_SUCCESS',
  'SEARCH_PROGRAMS_ERROR',
  'SEARCH_PROGRAMS_RESET_DATA',

  'UPDATE_PROGRAM_REQUEST',
  'UPDATE_PROGRAM_SUCCESS',
  'UPDATE_PROGRAM_ERROR',

  'DELETE_PROGRAM_REQUEST',
  'DELETE_PROGRAM_SUCCESS',
  'DELETE_PROGRAM_ERROR',
  'DELETE_PROGRAM_RESET_DATA',

  'CREATE_ADVANCED_PROGRAM_REQUEST',
  'CREATE_ADVANCED_PROGRAM_SUCCESS',
  'CREATE_ADVANCED_PROGRAM_ERROR',
  'CREATE_ADVANCED_PROGRAM_RESET_DATA',

  'UPDATE_ADVANCED_PROGRAM_REQUEST',
  'UPDATE_ADVANCED_PROGRAM_SUCCESS',
  'UPDATE_ADVANCED_PROGRAM_ERROR',
  'UPDATE_ADVANCED_PROGRAM_RESET_DATA',

  'SEND_EMAIL_TO_PARTICIPANTS_REQUEST',
  'SEND_EMAIL_TO_PARTICIPANTS_SUCCESS',
  'SEND_EMAIL_TO_PARTICIPANTS_ERROR',

  'CLONE_PROGRAM_REQUEST',
  'CLONE_PROGRAM_SUCCESS',
  'CLONE_PROGRAM_ERROR',

  'GET_ALL_PROGRAMS_REQUEST',
  'GET_ALL_PROGRAMS_SUCCESS',
  'GET_ALL_PROGRAMS_ERROR'
);

export interface IProgram {
  type: 'program';
  id: string;
  attributes: {
    name: string;
    code: string;
    organization_id: number;
    created_at: string;
    updated_at: string;
    reading_log: number;
    total_readers: number;
    total_books_read: number;
  };
}
