import createTypes from 'redux-create-action-types';

export default createTypes(
  'GET_AUTHORIZED_USER_REQUEST',
  'GET_AUTHORIZED_USER_SUCCESS',
  'GET_AUTHORIZED_USER_ERROR',

  'GET_AUTHORIZED_USER_DETAIL_REQUEST',
  'GET_AUTHORIZED_USER_DETAIL_SUCCESS',
  'GET_AUTHORIZED_USER_DETAIL_ERROR',

  'DELETE_AUTHORIZED_USER_REQUEST',
  'DELETE_AUTHORIZED_USER_SUCCESS',
  'DELETE_AUTHORIZED_USER_ERROR',
  'DELETE_AUTHORIZED_USER_RESET_DATA',

  'DELETE_ALL_AUTHORIZED_USERS_REQUEST',
  'DELETE_ALL_AUTHORIZED_USERS_SUCCESS',
  'DELETE_ALL_AUTHORIZED_USERS_ERROR',

  'ADD_AUTHORIZED_USER_REQUEST',
  'ADD_AUTHORIZED_USER_SUCCESS',
  'ADD_AUTHORIZED_USER_ERROR',
  'ADD_AUTHORIZED_USER_RESET',

  'SET_AUTHORIZED_USER_ACCESS',

  'UPDATE_AUTHORIZED_USER_REQUEST',
  'UPDATE_AUTHORIZED_USER_SUCCESS',
  'UPDATE_AUTHORIZED_USER_ERROR'
);
